# Codecov configuration
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_not_found: success

    patch:
      default:
        target: 70%
        threshold: 2%

# Comment configuration for PR coverage reports
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore files and directories
ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.mocks.dart"
  - "lib/main.dart"
  - "lib/firebase_options.dart"
  - "test/**"
  - "integration_test/**"
  - "android/**"
  - "ios/**"
  - "linux/**"
  - "macos/**"
  - "windows/**"
  - "web/**"
  - ".dart_tool/**"