// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo7GBWWy0C5Th7TkRPNrCBgvj98QUIf8s',
    appId: '1:554822623359:web:f68d0ca92b4d101b5f5f4a',
    messagingSenderId: '554822623359',
    projectId: 'diyetkent-67a1a',
    authDomain: 'diyetkent-67a1a.firebaseapp.com',
    storageBucket: 'diyetkent-67a1a.firebasestorage.app',
    measurementId: 'G-6TZDCDW0G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-Nb9wPdv2qF9JqDCw7bFpdg17yTowQM',
    appId: '1:554822623359:android:86f270dc93cd80d15f5f4a',
    messagingSenderId: '554822623359',
    projectId: 'diyetkent-67a1a',
    storageBucket: 'diyetkent-67a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUIfm8O4rD3Di2wVPOa5IoUaGkWOTEsE',
    appId: '1:554822623359:ios:9be2ea80c13cc4c65f5f4a',
    messagingSenderId: '554822623359',
    projectId: 'diyetkent-67a1a',
    storageBucket: 'diyetkent-67a1a.firebasestorage.app',
    iosBundleId: 'com.kenfroz.diyetkent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvUIfm8O4rD3Di2wVPOa5IoUaGkWOTEsE',
    appId: '1:554822623359:ios:9be2ea80c13cc4c65f5f4a',
    messagingSenderId: '554822623359',
    projectId: 'diyetkent-67a1a',
    storageBucket: 'diyetkent-67a1a.firebasestorage.app',
    iosBundleId: 'com.kenfroz.diyetkent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo7GBWWy0C5Th7TkRPNrCBgvj98QUIf8s',
    appId: '1:554822623359:web:6cc10bc821106de85f5f4a',
    messagingSenderId: '554822623359',
    projectId: 'diyetkent-67a1a',
    authDomain: 'diyetkent-67a1a.firebaseapp.com',
    storageBucket: 'diyetkent-67a1a.firebasestorage.app',
    measurementId: 'G-28YFN15S3Z',
  );
}
